name: Run repro

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: Python version to run repro.py with uv
        required: false
        default: "3.14.1"

permissions:
  contents: read

jobs:
  repro:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-14   # ARM
          - macos-13   # x86_64
    runs-on: ${{ matrix.os }}
    name: Run on ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

      - name: Run repro.py
        env:
          PYTHON_VERSION: ${{ inputs['python-version'] }}
        run: |
          uv run --with numpy -p "$PYTHON_VERSION" python repro.py
